version: '3.7'
services:
  frontend:
    build:
      context: .
    image: frontend
    network_mode: "host"
    ports:
      - 1111:1111
  backend:
    build:
      context: ./backend
    image: backend
    network_mode: "host"
    ports:
      - 8000:8000