version: '3.8'
services:
  frontend:
    build:
      context: .
    image: frontend
    ports:
      - 8501:8501
    links:
      - backend
  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - 8000:8000

