version: '3.7'
services:
  frontend:
    build:
      context: .
    image: frontend
    #network_mode: host
    ports:
      - 8501:8501
    links:
      - backend
  backend:
    build:
      context: ./backend
    image: backend
    #network_mode: host
    ports:
      - 8000:8000
