version: '3.8'
services:
  frontend:
    build:
      context: .
    image: frontend
    ports:
      - 8501:8501
    links:
      - backend
  backend:
    build:
      context: frontend/backend
    image: backend
    volumes:
      - C:\Users\faced\PycharmProjects\ml_services\vol:/code
    ports:
      - 8000:8000

